# Generated by Django 5.1.3 on 2024-12-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClinivet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.TextField(blank=True, default='No description provided', verbose_name='Description'),
        ),
    ]
